name: worldtriplink
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.2.0
  flutter_vector_icons: ^2.0.0
  url_launcher: ^6.2.4
  
  # Add these new dependencies
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  intl: ^0.18.1
  permission_handler: ^11.0.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  web_socket_channel: ^2.4.0
  stomp_dart_client: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/sedan.png
    - assets/images/suv.png
    - assets/images/suv_plus.png
    - assets/images/hatchback.png
    - assets/images/sedan_premium.png
    - assets/images/hatchback.png
    - assets/images/car_icon.png




flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # optional
