name: worldtriplink
description: A car rental application with professional architecture
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^5.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  intl: ^0.18.1
  location: ^5.0.0
  flutter_vector_icons: ^2.0.0
  google_maps_flutter: ^2.5.0
  
  # Added for tracking screens
  permission_handler: ^11.1.0
  stomp_dart_client: ^2.0.0
  geolocator: ^10.1.0
  flutter_polyline_points: ^2.0.0
  
  # Added for the migration
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  animated_text_kit: ^4.2.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
